# Generated by Django 4.2.3 on 2023-08-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
