# Generated by Django 4.2.3 on 2023-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_alter_doctor_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=30)),
                ('patient_name', models.TextField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=500)),
            ],
        ),
    ]
