# Generated by Django 4.2.3 on 2023-09-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0005_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='problem',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
