# Generated by Django 4.2.3 on 2023-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0006_alter_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ref_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
