# Generated by Django 4.2.3 on 2023-09-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0007_appointment_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
