# Generated by Django 4.2.3 on 2023-09-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0008_alter_appointment_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ref_no',
            field=models.CharField(default='unknown', max_length=10, primary_key=True, serialize=False),
        ),
    ]
