# Generated by Django 4.2.3 on 2023-09-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0009_remove_appointment_id_alter_appointment_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=100)),
                ('problem', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=15)),
                ('ref_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.appointment')),
            ],
        ),
    ]
